

import { db } from '../config/db.js';
import { targetCompanies } from '../shared/schema.js';


const eliteStartups = [
  "Airbnb", "Stripe", "Coinbase", "Dropbox", "Reddit", "DoorDash", "Instacart", 
  "Plaid", "Brex", "Figma", "Notion", "Vercel", "Supabase", "Linear", "Raycast", 
  "Scale AI", "OpenAI", "Anthropic", "Hugging Face", "Databricks", "Snowflake", 
  "Cloudflare", "Vanta", "Rippling", "Deel", "Gusto", "GitLab", "HashiCorp", 
  "Retool", "PostHog", "Sentry", "Netlify", "Apollo GraphQL", "Prisma", "Render", 
  "Fly.io", "Railway", "Neon", "PlanetScale", "Clerk", "Resend", "Algolia", 
  "Auth0", "Twilio", "SendGrid", "Robinhood", "Chime", "Revolut", "Monzo", 
  "Spotify", "Netflix", "Hulu", "Twitch", "Discord", "Slack", "Zoom", "Atlassian", 
  "Canva", "Miro", "Airtable", "Asana", "Monday.com", "ClickUp", "HubSpot", 
  "Salesforce", "Zendesk", "Intercom", "Gong", "Outreach", "Salesloft", "Toast", 
  "Square", "Shopify", "Epic Games", "Unity", "Roblox", "Niantic", "SpaceX", 
  "Anduril", "Palantir", "Flexport", "Opendoor", "Zillow", "Affirm", "Klarna", 
  "Peloton", "Oura", "Whoop", "Strava", "Duolingo", "Coursera", "Udemy", 
  "MasterClass", "Patreon", "Substack", "Medium", "Gumroad", "Zapier", "Make", 
  "Workato", "Segment", "Fivetran", "dbt Labs", "Airbyte", "Confluent", "MongoDB", 
  "Redis", "Elastic", "Splunk", "Datadog", "New Relic", "PagerDuty", "GitHub"
];


const myPreviousList = [
  "2iSolutions", "360 Degree Cloud Technologies", "5C Network", "5ireChain", 
  "63 moons Technologies", "6DegreesIT", "91social", "A-1 Technology", 
  "Aabasoft", "AAPNA Infotech", "ABM Knowledgeware", "Absolutdata Analytics", 
  "Abzooba", "Accelalpha", "ACCELQ", "Accops Systems", "Accubits Technologies", 
  "Accutech Power Solutions", "Acnovate Corporation", "Acropolis Infotech", 
  "Acropetal Technologies", "Acqueon", "Actis Technologies", "Acute Informatics", 
  "Acuver Consulting", "Adapty", "AdaniConneX", "Adarsh Solutions", "ADK Rage", 
  "Adea Solutions", "Aditi Consulting", "Aequor Technologies", "Aeries Technology Group", 
  "Aethereus", "Affle", "Affluent Global Services", "AFour Technologies", 
  "AG Technologies", "AGDATA, LP", "Aggne", "Agile CRM", "Agile Financial Technologies", 
  "Agile Global Solutions", "Agiliad", "Agri10x", "AIEnterprise Inc", 
  "Airdit Software Services", "AIS Technolabs", "AIT Global India", 
  "Akal Information Systems", "Akshay Software Technologies", "Alchemy Techsol India", 
  "Algonomy", "Algoworks", "Altezzasys Systems", "Altius", "Altruista Health", 
  "Altudo", "Alumnus Software", "Alvaria", "Ally.io", "Allyis", "Amantya Technologies", 
  "Amelia", "Ameyo", "Amiga Informatics", "Amnet Digital", "Amnet Systems", 
  "Ampcus Inc", "Ampl", "Ample Technologies", "AmpleLogic", 
  "AMREP SUPPLIER MANAGEMENT SERVICES", "Amrut Software", "AmZetta Technologies", 
  "Anaqua", "Anchanto", "Andor Tech", "Angara E-Commerce", "Ankercloud GmbH", 
  "ANM", "Anthelio Healthcare Solutions", "Antier Solutions", "Antra", 
  "AntWorks", "Anunta Tech", "Apar Peopleworld Software", "Apolis", "Apollo", 
  "ApMoSys Technologies", "apna", "Appcino Technologies", "Appiness Interactive", 
  "Appitsimple Infotek", "Applexus Technologies", "Appnomic", "Apps Business IT Solutions", 
  "AppsTek", "Apptware", "Appventurez", "AppViewX", "Aptos Retail", "Apty", 
  "AQM Technologies", "Arcadia", "Archwell", "Areteans", "ARK Infosolutions", 
  "Aress Software", "ARS Traffic & Transport Technology", "Artoon Solutions", 
  "Arya.ag", "ASK Automotive", "AspireNXT", "Aspiring Minds", "Asset Analytix", 
  "AST LLC", "Asta Crs Inc", "ATEM Software Solutions", "Atidiv", "Atlan", 
  "ATMECS Inc", "Atlas", "ATSG", "atyati Technologies", "Atyeti Inc", 
  "Aufait Technologies", "Aujas Cybersecurity", "Auriga IT Consulting", 
  "Aurus Inc", "Autoplant System India", "AutoRABIT", "Auzmor", "AVASO Technology Solutions", 
  "Avataar.Me", "Avanze", "Avesta Computer Services", "Awign", "Axeno", "Axioned", 
  "Ayoconnect", "Azilen Technologies", "Aztecsoft", "Azuga", "Baazi Games", 
  "Barry-Wehmiller International", "BBM", "BDS Services", "BDx Data Centers", 
  "Beetel", "BelWo Inc", "Benchmark IT Solutions", "Benison Technologies", 
  "BenQ India", "BETSOL", "Beyond Key", "Bidgely", "bijnis", "Birdeye", 
  "Bitla Software", "Bitwise India", "Bizom", "BiztechCS", "Blackstraw.ai", 
  "Blancco Technology Group", "Blazeclan Technologies", "Blubirch", "bluCognition", 
  "Blue Flame Labs", "BlueRose Technologies", "Blume Global", "bluepineapple", 
  "BoardEx", "BOB Tech Solutions", "Bobcares", "Boston Technology Corporation", 
  "Bourntec Solutions Inc", "BPO Convergence", "BPK Technologies", "BrainerHub Solutions", 
  "Brainly", "Brainvire Infotech", "Brane Enterprises", "Bridge Global", "BridgeLabz", 
  "BRIDGEi2i Analytics Solutions", "Briq", "BUDDI AI", "BukuWarung", "BURGEON IT SERVICES", 
  "Business Integra Inc", "BuyerForesight", "BuzzClan", "Byteridge", "C-Square Info Solutions", 
  "C-Zentrix", "C1X", "CaaStle", "Cadmaxx Solutions", "Caelius Consulting", 
  "Calcium", "California Software", "CallidusCloud", "Capermint Technologies", 
  "Capricot Technologies", "Capsitech", "Cartesian Consulting", "Cashapona Technologies", 
  "CashKaro.com", "Catalyst Business Solutions", "CatalystOne Solutions", "Catchpoint", 
  "Cavisson Systems", "Cavista", "CBNITS", "CDP India", "CDC Software", 
  "CEDCOSS Technologies", "Cegonsoft", "CEIPAL Corp.", "Ceinsys Tech", 
  "Celcom Solutions Global", "Celigo", "Cendyn", "Centre for Computational Technologies", 
  "Centroxy", "CEPTES Software", "Certa", "CETPA Infotech", "Changepond Technologies", 
  "Cheers Interactive", "Chimera Technologies", "Cientra", "CIGNEX Datamatics", 
  "CK Solutions", "Claim Genius", "Clarion Technologies", "Claritus Management Consulting", 
  "Clearbit", "Cleo", "CleverTap", "Cloud Analogy", "cloudEQ", "CloudMoyo", 
  "CloudSEK", "CloudThat", "cloudThing", "Cloudaction", "Clumio", "CodeCraft Technologies", 
  "CodeForce 360", "Codelogicx", "CodersBrain", "Codingmart Technologies", 
  "Codilar Technologies", "CoffeeBeans Consulting", "Cogencis Information Services", 
  "COGENT Infotech", "Cognitus", "Cognologix Technologies", "Cognus Technology", 
  "Collabera India", "Collaborate Solutions", "ColorTokens", "Colruyt India", 
  "coMakeIT", "CometChat", "CommerceIQ", "CompuMatrice", "Computer Power Group", 
  "Concentrix Tigerspike", "Concord Technologies", "Condeco", "Congruent Info-Tech", 
  "Consummate Technologies", "Consystent Infotech", "Contec Global", "Contentstack", 
  "ContractPodAi", "ControlCase", "Contus", "Conviva", "Core Solutions", 
  "CoreCard India", "CoreFlex Solutions", "Corent Technology", "CoreStack", 
  "Cotelligent", "Covalense Global", "Cozentus", "Crave InfoTech", "Crayon Data", 
  "Creative Capsule", "Creative Synergies Group", "Credence Analytics", 
  "Credencys Solutions", "Crestech Software", "CriticalRiver", "CRG Solutions", 
  "CRMIT Solutions", "CRMNEXT", "CropIn Technology", "CTS", "CUBE84", 
  "Customer Centria", "CustomerXPs", "Cynet Systems Inc", "Cyntexa", "Cyware", 
  "Cystems Logic Inc", "Daffodil Software", "Daloopa", "Damco Solutions", 
  "Dassault Systems", "Data Core Software", "Data Dynamics", "Data Glove", 
  "Data Intensity", "DATAECONOMY", "DCKAP", "Decimal Technologies", "Decision Minds", 
  "DeepTek", "Delphix", "Deque Systems", "Deqode", "Deskera", "Destek Infosolutions", 
  "Detect Technologies", "DEV IT SERV", "Dextara Digital", "DhanInfo", "Diabsolut Inc", 
  "Diamondpick", "Digiryte", "Digital Aptech", "Digital Convergence Technologies", 
  "Digital Refresh Networks", "Digitate", "Digite", "DigiValet", "DigiMantra Labs", 
  "Dimagi", "Dimiour", "Dion Global Solutions", "Diverse Lynx", "Dixit Infotech Services", 
  "DLT Labs", "Docmation", "DotPe", "Doyen Infosolutions", "Draup", "DreamOrbit", 
  "DreamSoft4u", "Dremio", "Drishti", "Drish Infotech", "DSRC", "DSM SOFT", 
  "Ducen", "Dukaan", "DVG", "DWAO", "Dynalog India", "DynPro", "Dyooti", 
  "EagleView India", "EA Team Inc", "Easy Eat AI", "Eastern Enterprise", 
  "EbixCash Financial Technologies", "eClinical Solutions", "Ecolab Digital Center", 
  "ECS Fin", "Edifecs", "Editorialist", "EDR Continuous Information", 
  "Education Management Solutions", "e-Emphasys Technologies", "eGain Corporation", 
  "EGlogics Softech", "Eightfold", "Eka Software Solutions", "Element5", 
  "Ellicium Solutions", "Elsner Technologies", "eMDs", "Embee Software", 
  "Embitel Technologies", "Encore Software Services", "Endurance / Newfold Digital", 
  "Enhance IT", "Enhancesys Innovations", "Enhops", "Enquero", "Enterprise Minds", 
  "Entropik Tech", "Envestnet", "Envoy Global", "EOX Vantage", "EPIKInDiFi", 
  "eProcurement Technologies", "EPSoft", "eProductivity Software", "eQ Technologic", 
  "Equifax India", "eReleGo Technologies", "eRevMax", "Esri India", "Estuate", 
  "Eternus", "ETG Digital", "Eton Solutions LP", "eTouch Systems", "Euclid Innovations", 
  "EverestEngineering", "EverQuote", "Everyday Health Group", "Evoke Technologies", 
  "Evolgence Telecom Systems", "Evolutyz Corp", "EvonSys", "Excelacom Technologies", 
  "Excelencia", "Excelra", "EXILANT Technologies", "Eximius Design", "Exly", 
  "Expedite Technology Solutions", "Experience.com", "Extentia Information Technology", 
  "Eze Software", "Fable Fintech", "Facile Services", "Facilio", "FCI CCM", 
  "Feat Systems", "Federal Soft Systems", "Feuji Inc", "Fidelis Corporate Solutions", 
  "fifthnote", "FiftyFive Technologies", "FIME", "Finesse Global", "Fintellix Solutions", 
  "Fint Solutions", "Fiorano Software", "FirstConnect Solutions", "Fiserv Insurance Solutions", 
  "Fission Labs", "FiveS Digital", "Flexasoft", "Flo Group", "FloBiz", "Flock", 
  "Fluentgrid", "Flytxt", "Focus Softnet", "Foodhub", "Ford Pro Charging", 
  "ForecastEra", "Fortanix", "Founder and Lightning", "Four Soft", "FourKites", 
  "Fourth Dimension Solutions", "FranConnect", "freeskout", "Fresh Gravity", 
  "Freshersworld.com", "Frontizo Business Services", "Frontier Business systems", 
  "FSL Software Technologies", "FUGO Services", "Fulcrum Digital Inc", "Fullestop", 
  "Futurism Technologies", "G10X", "Gaana", "Galaxy Weblinks Inc", "Gameopedia", 
  "Games24x7", "Games2win India", "Gameskraft", "Gathi Analytics", "Gateway Group of Companies", 
  "GeekLurn", "Gemini Consulting & Services", "Genisys Group", "Genzeon", "Geval6 Inc", 
  "Ginesys", "Girmiti Software", "GlobalEdge", "Glu Mobile", "GoKwik", "GoldenSource", 
  "Goodera", "Goods And Services Tax Network", "Gram Tarang Employability Training Services", 
  "Grasko Solutions", "Grassroots", "Great Place IT Services", "GreyOrange", "Growexx", 
  "Gupshup", "HackerEarth", "HAL", "Hammer", "Hanu Software", "Haptik", "Harbinger Group", 
  "Headout", "HeadSpin", "HealthAsyst", "HealthFore Technologies", "Health Prime", 
  "Helios Solutions", "HELM360", "Helpshift", "Heptagon Technologies", "Hevo Data", 
  "Hexagon Geosystems", "Hexagon Global", "High Peak Software", "Highstreet IT Solutions", 
  "Hirexa Solutions", "Hirect India", "Hitachi Solutions Asia Pacific", "Hitachi Solutions India", 
  "Hiver", "Hoonartek", "HPL", "Hubilo", "HulkApps", "i-Source Infosystems", "i2 Technologies", 
  "i2k2 Networks", "IAP Company", "iauro Systems", "IANT", "iB Hubs", "iBridge", 
  "iCS-global / INTECH", "Ideas2IT Technologies", "Ideassion Technology Solutions", 
  "ideyaLabs", "IDfy", "IDMWORKS", "IDrive Software India", "IDS NEXT Business Solutions", 
  "iFlair Web Technologies", "IFTAS", "iGlobal KPO Services", "IKF Technologies", "Iksula", 
  "iMark Infotech", "iMarque Solutions", "iMocha", "Impact Analytics", "Imperative Business Ventures", 
  "Impelsys", "Impiger Technologies", "impress.ai", "InApp", "Inatech", "IncNut Digital", 
  "Increff", "Incture", "Ind Innovation", "IndiaNIC Infotech", "Indus Net Technologies", 
  "Indus Valley Partners", "Indusface", "Innefu Labs", "Infinity", "Infobelt", 
  "Infodart Technologies", "iFocus Systec", "Infogen Labs", "Infollion Research Services", 
  "Infoplus Technologies UK", "Infosenseglobal Inc", "InfoStride", "Infosys Finacle", 
  "Infotech Global", "InfoVision Labs", "Infoworks.io", "InfraBeat Technologies", 
  "InfraCloud Technologies", "Infrasoft Technologies", "InheritX Solutions", "Innive Inc", 
  "Innobox", "Innohub Technologies Pte", "Innovapptive Inc", "Innoval Digital Solutions", 
  "Innovover Digital", "Innovsource", "INRY", "Insemi Technology Services", 
  "In-Solutions Global", "Inspirage", "Inspiredge IT Solutions", "InSync Solutions", 
  "Intech Systems", "Intelegain Technologies", "Intelegencia", "Inteliment", 
  "Intellect Bizware Services", "Intello Labs", "Interra Information Technologies", 
  "Interra Systems", "Intone", "Introlligent", "Inventech Info Solutions", "Inventive IT", 
  "Inventum", "IonIdea", "iPass", "IRIS Business Services", "Iron Systems", "ISHIR", 
  "iSolve Technologies", "iSource ITES", "ISSQUARED", "IT America Inc", "IT BY DESIGN", 
  "IT Services", "ITCG Solutions", "iTech India", "itelligence India Software Solutions", 
  "ITILITE", "ITOrizon", "ITTDigital", "Ittiam Systems", "Itlize Global", "iValue InfoSolutions", 
  "Ivy Mobility", "ixigo", "izmo", "Jagran New Media", "Janes", "Jeavio", "Jeevan Technologies", 
  "Jekson Vision", "JetSynthesys", "JioSaavn", "JMR Infotech", "JNET Technologies", 
  "JobsForHer", "Josh Software", "Joveo", "JSoft Solutions", "Julia Computing", 
  "Junglee Games", "Juntran Technologies", "Jupitice Justice Technologies", "JUSPAY", 
  "Kaizen Technologies", "Kale Logistics Solutions", "Kaleyra", "Kami Vision", 
  "Kapture CRM", "KARYA Technologies", "Kasmo", "Kastech Software Solutions Group", 
  "KBC Technologies Group", "Keka HR", "Kensium", "Keysight Network Visibility Test & Security", 
  "Kilowott", "Kissflow", "Kiya.ai", "Klaus IT Solutions", "KlearNow", "KnackForge", 
  "KOKO Networks", "Komprise", "Konica Minolta Business Solutions India", "Konverge Technologies", 
  "Kore.ai", "Kovaion Consulting", "KPI Partners", "Krish Compusoft Services", 
  "Krish TechnoLabs", "KritiKal Solutions", "Kriya IT", "Kumaran Systems", "Kutir Corporation", 
  "La Net Team Software Solution", "LabVantage Solutions", "LambdaTest", "LARVOL", 
  "Lauren Information Technologies", "LeadIQ", "Leader Investment Group - LIG", "Leading IT", 
  "LearnQuest", "Learning Spiral", "Leena AI", "Lentra", "Leoforce", "Lera Technologies", 
  "Lighthouse Info Systems", "Lipi Data Systems", "LiquidHub", "Lirik", "Litmus7", 
  "Liventus", "Lockstep", "Loco", "LocoNav", "Locuz", "Logisoft Technologies", 
  "LoginRadius", "Logixal Inc", "Lorhan IT", "LRN", "LRS Services (P)", "LSA Recruit", 
  "Lumel", "Luminescent Digital", "Lumiq", "M3BI", "Maantic Inc", "Macrosoft", "Magic EdTech", 
  "Magnasoft", "Mahindra Satyam BPO", "Maintec Technologies", "Manappuram Comptech & Consultants", 
  "ManekTech", "MangoApps", "Manthan", "Mantra", "Mantra Labs", "Mantra Softech", 
  "Maropost", "MasterSoft ERP Solutions", "MatchPoint Solutions", "Matellio", "Maven Wave", 
  "Mawai Infotech", "MaxVal Group", "McKinley Rice", "MediaAgility", "Medline India", 
  "Megasoft Solutions India", "Mergen IT LLC", "Merkle Science", "MetaMorphoSys Technologies", 
  "MetaOption LLC", "METRO SERVICES", "Microexcel Inc", "MicroObjects", "Micropro Software Solutions", 
  "Microlise", "Milkbasket", "MINDTREE", "MindCraft Software", "Mindfire Solutions", 
  "Mindgate Solutions", "Mindpool Technologies Inc", "Mindstix Software Labs", "Mindteck India", 
  "Mindtickle", "Minfy", "Minosha India", "Mirafra Technologies", "mjunction services", 
  "MobileCoderz", "Mobiloitte", "Modefin", "mokSa Technologies", "Monarch Info Tech Services", 
  "Montran Corporation", "MoEngage", "Moolya", "Moonfrog Labs", "Mosambee", "MPS Interactive Systems", 
  "MResult", "MSRcosmos LLC", "MTX Group", "MultiQoS Technologies", "MulticoreWare Inc", 
  "Mutual Mobile", "Muvi.com", "MyGate", "MyGlamm", "Mygo Consulting", "Mylo", 
  "Mysense Technologies", "Naico ITS", "Nanostuffs", "Napier Healthcare", "Narvar", 
  "Nascent Info Technologies", "NASSCOM", "NathCorp", "National Computer Systems", 
  "Nature Technologies", "NAVA Software Solutions", "Naviga India", "Navis", 
  "NCDEX e Markets", "Near", "NEC Software Solutions", "NeelBlue Technologies", "Neewee", 
  "Neova Solutions", "Neovatic Technologies", "NeST Digital", "Net Business Solutions", 
  "Net Solutions", "NetCom Learning", "NetConnectGlobal", "Netcon Technologies India", 
  "Netcore Cloud", "Netenrich", "Netmagicsolutions / NTT DATA", "Netomi", "Netrix", 
  "Netrovert Software", "Netradyne", "Netsmartz", "Netwoven", "Neudesic Technologies", 
  "Neutrino Tech Systems", "Nevaeh Technology", "Neviton Softech", "Newt Global Consulting", 
  "NewVision Software", "Nexgen IOT Solutions", "Nexval Group", "Nichi-In Software Solutions", 
  "Nickelfox Technologies", "NielsenIQ", "Niftel Communications", "NIIT Technologies", 
  "Nirvana Solutions", "Nitor Infotech", "Niveus Solutions", "Niyuj", "Noblesoft Technologies", 
  "Northgateps / NEC Software Solutions", "Norwin Technologies", "Novopay", "NovelVox", 
  "NR Consulting", "Nsight", "NTrust Infotech", "NTT DATA", "Numeric Technologies", 
  "Nuvento Inc", "NuWare", "NVISH Solutions", "NxtGen Infinite Datacenter", "O2F INFO SOLUTIONS", 
  "Object Technology Solutions India", "ObjectFrontier Software", "Observe.AI", "Olive Technology", 
  "OmnePresent Technologies", "Onama Consultants", "OnDemand Agility Solutions", "ONE BCG", 
  "one.com", "OneGlobe", "OnGraph Technologies", "Open Destinations", "Operative", "Opsera", 
  "OpsHub", "Opt IT Technologies", "Optimize IT Systems", "Optimus Information", 
  "Optimum Solutions", "Optym", "Opus Consulting Solutions", "Orange Business Services", 
  "Orbit Techsol", "Orcapod", "Ospyn Technologies", "Pacific Global", "Paktolus Solutions", 
  "Palni Inc", "Panamax", "Panamax Infotech", "PandoCorp", "Panzer Technologies", 
  "ParadigmIT", "Paramatrix Technologies", "Pathlock", "Pavilion", "Paycraft Solutions", 
  "Paytm Insider", "Payoda Technology", "PC Solutions", "Pelican.ai", "Pentagon System and Services", 
  "People10 Technologies", "Percipere", "Perennial Systems", "Perfios Software Solutions", 
  "Perpetuuiti Technosoft PTE", "Pesto Tech", "Petro IT", "Pharmarack", "phData", 
  "Phoenix Advanced Softwares", "Pinga Solution", "Pixentia", "Placement Services", 
  "Planful", "PlanSource", "Platform9 Systems", "Plivo", "Pocket FM", "Polaris", "Polygon", 
  "Porteck Corporation", "Posidex", "Potomac Technologies", "Pragmasys Consulting", 
  "Pramati Technologies", "Pratham Software", "Pratiti Technologies", "Precision Technologies", 
  "PreludeSys", "Prescient Technologies", "PRIMUS Global Technologies", "Privafy", "Probe42", 
  "ProdEx Technologies", "Prodevans Technologies", "Profinch", "Progility Technologies", 
  "Promact Infotech", "Protean eGov Technologies", "ProTechmanize Solutions", "ProV International", 
  "Provar Testing", "Prowess Software Services", "Proximity Works", "PSRTEK", "PureSoftware", 
  "PURVIEW", "Purplle.com", "Pyxis One", "Q3 Technologies", "QA InfoTech", "QBA Worldwide", 
  "QBrainX Inc", "qSEAp Infotech", "QSS Technosoft", "QUADRIFIC MEDIA", "Quadrant Resource", 
  "QualiZeal", "Quantela", "Quark Software", "Quarks", "Quartic.ai", "Quest Innovative Solutions", 
  "QuestionPro", "Quess GTS", "Quinbay", "Qwikcilver Solutions", "Quytech", "RAH Infotech", 
  "Rahi", "RandomTrees", "Rane t4u", "Rang Technologies Inc", "Rapid Innovation", 
  "Rapidflow Inc", "RapidValue", "RateGain", "Rayden Interactive", "RDAlabs", 
  "Real Time Data Services", "realworld one", "ReBIT", "Recro", "RecruitNXT", 
  "Reflections Info Systems", "Relationship Science", "Relevance Lab", "Reliable Software", 
  "Religare Technova", "Reltio", "Replicon", "Reputation.com", "ReshaMandi", "Resilience InfoTech", 
  "Responsive Media Tech Services", "Resulticks", "Reverie Language Technologies", 
  "RevGurus Inc", "Reward360 Global Services", "RGI Group", "RIA Advisory", "Rigved Technologies", 
  "RioMed", "Rite Software", "Rizzle", "RLabs Enterprise Services", "RM Education Solutions India", 
  "RNF Technologies", "Rooter App", "RPS Consulting", "Rrootshell Technologiiss", 
  "RT Network Solutions", "RT Outsourcing Services", "rtCamp", "RudderStack", "RVU India", 
  "RxLogix", "sa.global", "SA Technologies", "Saicon", "SafexPay", "Sagarsoft", "Saggezza", 
  "Sailotech", "Sakhatech Information Systems", "Salesken", "Saltside", "Sandhata Technologies", 
  "Saransh Inc", "Sarvatra Technologies", "Saviance Technologies", "Saviant Consulting", 
  "Savantis Solutions LLC", "Saviynt", "Savvysoft Technologies", "SCIKEY", "SCIO Health Analytics", 
  "Scienaptic AI", "SCORG International Consulting", "Seanergy Digital", "Sears Holdings India", 
  "SE2", "Secomind.AI", "Securonix", "Secure-24", "SecureKloud Technologies", "Securelynkx Networks", 
  "Sedin Technologies", "Selectsys India", "Select Source International", "Sellcraft Global Solutions", 
  "SELP", "SenecaGlobal", "Senrysa Technologies", "Sense", "Sentieo", "Serole Technologies", 
  "ServiceMax", "Servosys Solutions", "Shell Transource", "Shivaami Cloud Services", "Shipsy", 
  "Shore Group Associates", "ShoreWise Consulting", "ShopX", "SID Global Solutions", 
  "Sierra Atlantic", "SightSpectrum LLC", "Sigmoid", "Sigma-Byte Computers", 
  "Signity Software Solutions", "SigTuple", "Silverline", "Simplify Healthcare", "Simpplr", 
  "Singsys Pte", "SirionLabs", "SISA", "Sixth Energy Technologies", "SixSails", "Skience", 
  "Skilrock Technologies", "Skillmine Technology Consulting", "Skoruz Technologies", "Skuad", 
  "SkyOnn Technologies", "SLK Group / VFI SLK", "Smaartt Digital Consulting", "Smart IMS", 
  "Smartedge Solutions", "SmartKargo", "SMARTe", "smartSense Consulting Solutions", "SmarTek21", 
  "SMS-Magic", "Softcell Technologies Global", "Softdel", "Softenger", "Softlogic Systems", 
  "Softnautics", "SoftNice", "Softobiz Technologies", "Softpath System", "SoftSol", "Softura", 
  "Software Data (India) - SDIL", "Solace Infotech", "Soliton Technologies", "Solix Technologies", 
  "Soltius Indonesia", "Solugenix", "Solution Analysts", "Solverminds Solutions & Technologies", 
  "Soroco", "Sourcebits Digital", "SourceFuse Technologies", "SourceTrace", 
  "Span Technology Services", "Spanco BPO", "SpanIdea Systems", "Spenmo", "Spiceworks Ziff Davis", 
  "Sphinx Worldbiz", "SpringML", "Springworks", "SrinSoft Technologies", "SRINI PHARMACEUTICALS", 
  "SRS Web Solutions", "SSIT", "SSM InfoTech Solutions", "ST Telemedia Global Data Centres", 
  "STAND 8 Technology Services", "Stanley David and Associates", "StartUP", "Stellapps Technologies", 
  "Stellar Information Technology", "Sterling Software", "StockEdge", 
  "StrategicERP Business Automation Solutions", "StraViso", "Streamoid", "Successive Technologies", 
  "Sugal & Damani", "SugarBox Networks", "Suki", "SUMERU SOFTWARE SOLUTIONS", "SumTotal Systems", 
  "Sun Life", "SunTec Business Solutions", "SuperOps.ai", "Supply Wisdom", "SupraES", "SupraSoft", 
  "SurePrep LLC", "Suyati Technologies", "SVAM International", "Symphony Corporation", 
  "Symphony RetailAI", "Symphony SummitAI", "Symbiosis Technologies", "SysCloud", "Systango", 
  "System Soft Technologies", "Systematix Infotech", "Systel", "Sysvine Technologies", 
  "TAAL Tech", "Taashee Linux Services", "Taazaa Inc", "TAC", "TactTree LLP", "Talentica Software", 
  "TALENTPLOYER", "Talisma", "Talview", "Tanla Platforms", "Tanisha Systems", "Tarento Group", 
  "Tata CLiQ", "Tata Communications", "Tata Digital", "Tata Technologies, Pune", 
  "TATWA Technologies", "Tavisca", "Team Recykal", "Tech Connect Services", "TechBlocks", 
  "TechAffinity", "TechAhead", "TechGenies", "Techila Global Services", "Techmango Technology Services", 
  "TechMatrix Consulting", "TechnoBind Solutions", "Technodysis", "TechnoGen", "TechnoIdentity", 
  "Techpoint", "Techspian", "TechTammina LLC", "TechTree IT Systems", "Techversant", "Technovert", 
  "Tecplix Technologies", "Tejora", "TekLink International", "Teknorix", "Teksun Inc", 
  "TEKsystems Global Services in India", "Telliant Systems", "Tenerity India", "Teqfocus", 
  "Tera Software", "Terralogic", "TestingXperts", "TestVagrant Technologies", "Tetrasoft", 
  "The MIL Corporation", "The Scalers", "thinkbridge", "Thirdware Solution INC", "ThoughtSpot", 
  "TOMIA", "ToneTag", "TOPS Technologies", "Toshiba Software (India)", "Total IT Global", 
  "TraceLink", "Trangile Services", "Transact Campus Inc", "Transact Global", "TransUnion CIBIL", 
  "Trantor", "TravClan", "Trell", "Trellissoft", "TRIARQ Health India", "Tricon Infotech", 
  "Trilogy Innovations", "Trimax Americas", "Trinamix Inc", "Trineo", "Tringapps", 
  "TrioTree Technologies", "Tripoto", "TripStack", "TruckX Inc", "TRUGlobal", 
  "Truminds Software Systems", "TrusTrace", "TrueTech Solutions", "Truecaller", "Tulip Interfaces", 
  "Tuyasmart India", "TVS Next", "tyfone", "U2opia Mobile", "U3 Infotech", "Ubique Systems", 
  "Ultimate Digital Solutions", "Umbrella Infocare", "Unicommerce eSolutions", "Uneecops Technologies", 
  "UniFocus", "UniqueHire Consulting LLP", "Unilog", "Uniphore", "Unitech", "United Online", 
  "Urban Ladder", "UrbanPiper", "USEReady", "Ushur", "UST BlueConch Technologies", "Utthunga", 
  "Utopia Global", "V2Soft", "V2Solutions", "Vaave", "Vagaro Inc", "Vaisesika Consulting", 
  "Valenta", "Valethi Technologies", "ValGenesis", "Valiance Solutions", "ValueCoders", 
  "ValueFirst", "Valuepitch E Technologies", "Value Point Systems", "Vasudhaika Software", 
  "Verifaya Corporation", "Verinite", "Verisys Corporation", "Verolt", "VerSe Innovation", 
  "Versa Networks", "Vertex Global Services", "VFI SLK", "Vibrent Health", "Vincit", 
  "Vinculum Group", "Virinchi", "Virsec Systems", "Virtual Height IT Services", "Visible Alpha", 
  "Visteon Technical And Services Centre", "VLink Inc", "VMock", "VNC Digital Services", 
  "VOLANSYS", "Volante Technologies", "Votary Softech Solutions", "Vouchagram India", "VRIZE", 
  "VT Netzwelt", "vTech Solution", "Vuram", "Vyom Labs", "Vymo", "VySystems", 
  "W3villa Technologies", "WAISL", "Wavicle Data Solutions", "Weaverbird Engineering & Technology", 
  "WebEngage", "Webguruz Technologies", "Webkul", "WeblineIndia", "WebMobril Technologies", 
  "Webomaze Technologies", "WEBSKITTERS TECHNOLOGY SOLUTIONS", "WeP Peripherals", "West Agile Labs", 
  "WFX - World Fashion Exchange", "Wibmo", "Wilco Source", "Windmill", "Wingify", "Winjit Technologies", 
  "WinWire Technologies", "WisdmLabs", "Wobot.ai", "Wolters Kluwer ELM Solutions", "WorkFusion", 
  "WorkIndia", "WorkInSync", "Workforce Logiq", "WovV Technologies", "WRENCH Solutions", 
  "Writer Information", "Wunderman Thompson Commerce", "Wunderman Thompson MSC", "Xangars Solutions", 
  "Xansa plc", "XDuce", "Xeno", "Xento Systems", "Xicom Technologies", "Xoxoday", "XTGlobal", 
  "xto10x", "Y Media Labs", "Yexle", "Yotta Infrastructure Solutions", "Zaggle Prepaid Ocean Services", 
  "ZapCom Group Inc", "zCon Solutions", "Zelite Solutions", "Zemoso Technologies", "Zen & Art", 
  "Zendrive", "Zenith Software", "Zenoti", "ZenQ", "Zensark", "Zentek Infosoft", "Zenwork", 
  "ZeOmega", "Zerone Consulting", "ZIGRAM", "ZiMetrics Technologies", "Zoondia", "Zuci Systems", 
  "Zumen Inc", "Zuper"
];


const allCompanies = [...eliteStartups, ...myPreviousList];

// Converts company name to a URL-safe board token
function generateBoardToken(companyName: string): string {
  return companyName.toLowerCase().replace(/[^a-z0-9]/g, '');
}

async function seedDatabase() {
  console.log(`🌱 Starting Seeder: Processing ${allCompanies.length} companies...`);

  const formattedTargets = allCompanies.map(name => {
    return ({
      name: name,
      atsProvider: 'greenhouse',
      boardToken: generateBoardToken(name),
      isActive: true,
    };
  });

  try {
    await db.insert(targetCompanies)
      .values(formattedTargets)
      .onConflictDoNothing({ target: targetCompanies.boardToken });

    console.log(`✅ Success! Injected Command Center with target companies.`);
    process.exit(0);
  } catch (error: any) {
    console.error(`❌ Seeder Failed:`, error.message);
    process.exit(1);
  }
}

seedDatabase();